extends: airbnb
plugins:
  - react
  - jsx-a11y
  - import
  - jest
settings:
  import/resolver:
    webpack:
        config: './config/webpack.config.dev.js'
env:
  browser: true
  jquery: true
  jest: true
parserOptions:
  ecmaVersion: 8
rules:
  no-plus-plus: 0
  no-use-before-define: 0
