language: node_js

node_js:
  - 8

cache: yarn

jobs:
  include:
    - stage: test
      script: npm run test

    - stage: lint
      script: echo one
      script: echo two

    - stage: build
      script: npm run test