language: node_js

node_js:
  - 8

env:
  - NODE_ENV=production

cache: yarn

jobs:
  include:
    - stage: test
      script: yarn install --production=false
      script: npm run test

    - stage: lint
      script: npm run lint

    - stage: build
      script: npm run test