language: node_js

node_js:
  - 8

env:
  - NODE_ENV=production

install:
  - stage setup
  - npm install

test:
  - stage test
  - npm run test

lint:
  - stage lint
  - npm run lint

build:
  - npm run build