language: node_js

node_js:
  - 8

cache:
  yarn: true
  timeout: 1000

jobs:
  include:
    - stage: test
      script: npm run test

    - stage: lint
      script: npm run lint
    - script: npm run lint:css

    - stage: build
      script: npm run build
