language: node_js

node_js:
  - 8

# env:
#   - NODE_ENV=production

cache: yarn

jobs:
  include:
    - stage: install
      script: yarn install --production=false

    - stage: test
      script: npm run test

    - stage: lint
      script: npm run lint

    - stage: build
      script: npm run test